--- #Esta playbook tiene que ser ejecutada con las credenciales de WinRM
- name: Run Updates on Terminal Servers then wait 7 mins #Ejecutar actualizaciones en los servidores terminales y esperar 7 minutos
  hosts: "{{group_name}}"
  tasks:
    ansible.windows.win_updates:
      category_names: #Categorias de actualizaciones
        - Application
        - CriticalUpdates
        - DefinitionUpdates
        - SecurityUpdates
        - Updates
      accept_list: #Lista de actualizaciones a instalar
        - KB4093120
    state: installed
    reboot: yes
    reboot_timeout: 420 #Tiempo de espera para reiniciar
