--- #Esta playbook tiene que ser ejecutada con las credenciales de WinRM
- name: Update
  hosts: "{{group_name}}"
  tasks:
#    - name: Example from an Ansible Playbook
#      ansible.builtin.ping:
      
    - name: Search-only, return list of found updates (if any), log to C:\ansible_wu.txt
      ansible.windows.win_updates:
        category_names: '*'
        state: searched
      register: update_info
